name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v3

    - name: Run Linter
      run: |
        echo "Running linter..."
        echo "Linting complete."

    - name: Run Tests
      run: |
        echo "Running tests..."
        echo "All tests passed!"
