name: Parallel Job Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Linter
      run: python -m pip install --upgrade pip flake8

    - name: Run Linter
      run: flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Test Dependencies
      run: python -m pip install --upgrade pip pytest

    - name: Debug Test Collection
      run: pytest --collect-only

    - name: Run Tests
      run: pytest

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Build Dependencies
      run: python -m pip install --upgrade pip setuptools

    - name: Build Package
      run: python setup.py build
