name: Parallel Job Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Run Linter
      run: flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Run Tests
      run: pytest

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Package
      run: python setup.py build
