name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      build-command:
        description: "The command to build the project."
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v3

    - name: Run Build Command
      run: ${{ inputs.build-command }}
